(require 'org-page)
(setq op/repository-directory "~/Documentos/personal-blog/")
(setq op/site-domain "https://www.maxxcan.com")
(setq op/site-main-title "Blog Personal de Maxxcan")
(setq op/site-sub-title "Blog sobre tecnología y diseño")
(setq op/theme 'notxor)
(setq op/tag-rss t)
(setq op/personal-github-link "https://www.github.com/maxxcan")
(setq op/site-preview-directory "~/Documentos/personal-blog/blog")
