 (defun header-org-mode (language)
  "Make a template at point."
  (interactive
   (let ((languages '("Generic" "HTML" "LaTeX" "Beamer" "Reveal")))
     (list (ido-completing-read "To which export: " languages))
     )
   )

  (when (string= language "Generic")
    (progn
      (insert (format "#+TITLE:\n"))
      (insert (format "#+AUTHOR:\n"))
      (insert (format "#+LANGUAGE: es \n"))
      (insert (format "#+OPTIONS:   toc:1\n"))
      (insert (format "#+TOC: headlines 3\n\n"))
      )
    )

  (when (string= language "HTML")
    (progn
      (insert (format "#+TITLE:\n"))
      (insert (format "#+AUTHOR:\n"))
      (insert (format "#+LANGUAGE: es\n"))
      (insert (format "#+OPTIONS:   toc:1\n"))
      (insert (format "#+TOC: headlines 3\n"))
      )
    )

  (when (string= language "LaTeX")
    (progn
      (insert (format "#+TITLE:\n"))
      (insert (format "#+AUTHOR:\n"))
      (insert (format "#+LANGUAGE: es\n"))
      (insert (format "#+LATEX_CLASS: article\n"))
      (insert (format "#+LATEX_CLASS_OPTIONS: [spanish,a4paper]\n"))
      (insert (format "#+LATEX_HEADER: \\usepackage{color}\n"))
      (insert (format "#+LATEX_HEADER: \\usepackage[spanish]{babel}\n"))
      (insert (format "#+LATEX_HEADER: \\textwidth=17cm\n"))
      (insert (format "#+LATEX_HEADER: \\oddsidemargin=0.5cm\n\n"))

      )
    )
  (when (string= language "Beamer")
    (progn
      (insert (format "#+TITLE:\n"))
      (insert (format "#+AUTHOR:\n"))
      (insert (format "#+DATE:\n"))
      (insert (format "#+OPTIONS: toc:nil num:nil\n"))
      (insert (format "#+STARTUP: beamer\n"))
      (insert (format "#+OPTIONS: toc:nil\n"))
      (insert (format "#+LaTeX_CLASS: beamer\n"))
      (insert (format "#+LaTeX_CLASS_OPTIONS: [t]\n"))
      (insert (format "#+LaTeX_HEADER: \\usetheme{Madrid}\n"))
      (insert (format "#+LaTeX_HEADER: \\usepackage{mathpazo}\n"))
      (insert (format "#+LaTeX_HEADER: \\usepackage{stmaryrd}\n"))
      (insert (format "#+LaTeX_HEADER: \\DeclareMathOperator*{\\argmin}{arg\\,min}\n"))
      (insert (format "#+LaTeX_HEADER: \\DeclareMathOperator*{\\argmax}{arg\\,max}\n"))
      (insert (format "#+BEAMER_FRAME_LEVEL: 2\n\n"))
      ))
  (when (string= language "Reveal")
    (progn
      (insert (format "#+TITLE:\n"))
      (insert (format "#+AUTHOR:\n"))
      (insert (format "#+EMAIL:\n"))
      (insert (format " "))
      (insert (format "#+REVEAL_ROOT: file:/opt/reveal.js/\n"))
      (insert (format "#+OPTIONS: reveal_center:t reveal_progress:t reveal_history:nil reveal_control:\n"))
      (insert (format "#+OPTIONS: reveal_rolling_links:t reveal_keyboard:t reveal_overview:t num:nil\n"))
      (insert (format "#+OPTIONS: reveal_width:1200 reveal_height:800\n"))
      (insert (format "#+OPTIONS: toc:1\n"))
      (insert (format "#+REVEAL_MARGIN: 0.1\n"))
      (insert (format "#+REVEAL_MIN_SCALE: 0.5\n"))
      (insert (format "#+REVEAL_MAX_SCALE: 2.5\n"))
      (insert (format "#+REVEAL_TRANS: cube\n"))
      (insert (format "#+REVEAL_THEME: league\n"))
      (insert (format "#+REVEAL_HLEVEL: 3\n"))
      (insert (format "#+REVEAL_HEAD_PREAMBLE: <meta name="description" content=" ">\n"))
      (insert (format "#+REVEAL_POSTAMBLE: <p> Created by . </p>/n"))
      (insert (format "#+REVEAL_PLUGINS: (markdown notes)/n/n"))
      ))
  )

(provide 'header-org-mode)
